# Default values for srm-purchase-cooperation.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.choerodon.com.cn/hzero-srm/srm-purchase-cooperation
  pullPolicy: Always

envFrom:
  - isrm-cm

env:
  open:
    # 消费组
    CONSUMER_GROUP: SRM-PURCHASE-COOPERATION-${ENV}
    JAVA_OPTS: "-Xms1024m -Xmx2048m"

apm:
  enabled: false
  plugins:
    - name: skywalking
      image: swr.cn-east-2.myhuaweicloud.com/zhenyun/skywalking:6.6.0
      enabled: false
      java_opts: >-
        -javaagent:/Charts/skywalking/skywalking-agent.jar
        -Dskywalking.agent.service_name=$(PASS_APP_NAME)
    - name: glowroot
      image: swr.cn-east-2.myhuaweicloud.com/zhenyun/glowroot:0.13.5
      enabled: false
      java_opts: >-
        -javaagent:/Charts/glowroot.jar
        -Dglowroot.agent.id=$(PASS_APP_NAME)
        -Dglowroot.agent.rollup.id=$(ENV)
        -Dglowroot.collector.address=$(GLOWROOT_COLLECTOR_ADDRESS)
    - name: pinpoint
      image: swr.cn-east-2.myhuaweicloud.com/zhenyun/pinpoint:1.8.5
      enabled: true
      configmap: pinpoint-configmap
      java_opts: >-
        -javaagent:/Charts/pinpoint/pinpoint-bootstrap-1.8.5.jar
        -Dpinpoint.applicationName=$(PASS_APP_NAME)
        -Dpinpoint.agentId=$(PASS_UUID)

metrics:
  path: /actuator/prometheus
  group: spring-boot

logs:
  parser: spring-boot

persistence:
  enabled: false
  ## A manually managed Persistent Volume and Claim
  ## Requires persistence.enabled: true
  ## If defined, PVC must be created manually before volume will be bound
  # existingClaim:
  # subPath:

service:
  enabled: false
  type: ClusterIP
  port: 8440
  name: srm-purchase-cooperation
deployment:
  managementPort: 8441

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources,such as Minikube. If you do want to specify resources,uncomment the following
  # lines,adjust them as necessary,and remove the curly braces after 'resources:'.
  limits:
    cpu: 1000m
    memory: 2.2Gi
  requests:
    cpu: 100m
    memory: 1.2Gi

imagePullSecrets:
  enabled: true
  secrets:
    - name: default-secret

livenessProbe:
  enabled: true
  ## 仅在type为tcpSocket和httpGet下生效，默认取.deployment.managementPort
  type: exec
  ## 仅在type为exec下生效
  command: 
    - /bin/sh
    - '-c'
    - 'nc -z localhost 8440'
  ## 仅在type为tcpSocket和httpGet下生效
  #port: 8440
  ## 仅在type为httpGet下生效, path默认为 /actuator/health, host若不设置，则默认为pod ip，scheme可选值为HTTP、HTTPS, 默认为HTTP
  #path: /
  #scheme: HTTP
  #host:
  initialDelaySeconds: 180
  timeoutSeconds: 10
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3

readinessProbe:
  enabled: true
  ## 可选项为exec、tcpSocket、httpGet
  type: exec
  ## 仅在type为exec下生效
  command: 
    - /bin/sh
    - '-c'
    - 'curl localhost:8441/actuator/health'
  ## 仅在type为tcpSocket和httpGet下生效，默认取.deployment.managementPort
  #port: 8441
  ## 仅在type为httpGet下生效, path默认为 /actuator/health, host若不设置，则默认为pod ip，scheme可选值为HTTP、HTTPS, 默认为HTTP
  #path: /
  #scheme: HTTP
  #host:
  initialDelaySeconds: 180
  timeoutSeconds: 10
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3

startupProbe:
  enabled: false
  ## 可选项为exec、tcpSocket、httpGet
  type: exec
  ## 仅在type为exec下生效
  command: 
    - /bin/sh
    - '-c'
    - 'curl localhost:8441/actuator/health'
  ## 仅在type为tcpSocket和httpGet下生效，默认取.deployment.managementPort
  #port: 8441
  ## 仅在type为httpGet下生效, path默认为 /actuator/health, host若不设置，则默认为pod ip，scheme可选值为HTTP、HTTPS, 默认为HTTP
  #path: /
  #scheme: HTTP
  #host:
  timeoutSeconds: 10
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 30
